INSERT INTO CONFIGURACAO (CHAVE, VALOR) VALUES ('IMPOSTO_ABASTECIMENTO', 0.13);

INSERT INTO TANQUE (NOME, TIPO_COMBUSTIVEL, ESTOQUE_ATUAL_L, VALOR_LITRO)
VALUES ('GASOLINA', 'GASOLINA', 30000, 5.99);
INSERT INTO TANQUE (NOME, TIPO_COMBUSTIVEL, ESTOQUE_ATUAL_L, VALOR_LITRO)
VALUES ('DIESEL', 'DIESEL',  30000, 6.09);

INSERT INTO BOMBA (TANQUE_ID, CODIGO, DESCRICAO)
SELECT TANQUE_ID, 'B01', 'BOMBA GASOLINA 01' FROM TANQUE WHERE NOME='GASOLINA';
INSERT INTO BOMBA (TANQUE_ID, CODIGO, DESCRICAO)
SELECT TANQUE_ID, 'B02', 'BOMBA GASOLINA 02' FROM TANQUE WHERE NOME='GASOLINA';
INSERT INTO BOMBA (TANQUE_ID, CODIGO, DESCRICAO)
SELECT TANQUE_ID, 'D01', 'BOMBA DIESEL 01' FROM TANQUE WHERE NOME='DIESEL';
INSERT INTO BOMBA (TANQUE_ID, CODIGO, DESCRICAO)
SELECT TANQUE_ID, 'D02', 'BOMBA DIESEL 02' FROM TANQUE WHERE NOME='DIESEL';
